-- SET PRODUCTOS
INSERT INTO producto (ID, NOMBRE, PRECIO, GENERA_CUPON, PORCENTAJE_CUPON_GENERAR)
VALUES(1, 'Solo', 10, false, 0);
INSERT INTO producto (ID, NOMBRE, PRECIO, GENERA_CUPON, PORCENTAJE_CUPON_GENERAR)
VALUES(2, 'Parejas', 20, true, 10);

-- SET CITAS
INSERT INTO cita (ID, CEDULA_CLIENTE, FECHA_GENERACION, FECHA_SOLICITUD, PRECIO_PRODUCTO, ID_CUPON, ID_PRODUCTO)
VALUES(1,'1234', '2020-10-10', '2020-10-12', 20, NULL, 2);

-- SET CUPONES
INSERT INTO cupon (ID, PORCENTAJE_DESCUENTO, USADO, ID_CITA)
VALUES(1, 10, FALSE, 1);