INSERT INTO producto (ID, NOMBRE, PRECIO, GENERA_CUPON, PORCENTAJE_CUPON_GENERAR)
VALUES(1, 'Solo', 10, false, 0);
INSERT INTO producto (ID, NOMBRE, PRECIO, GENERA_CUPON, PORCENTAJE_CUPON_GENERAR)
VALUES(2, 'Parejas', 18, true, 10);